### ISSUE TITLE
Add --help option

### ISSUE THREAD

**Issue by strager** [strager/quick-lint-js#11]
Add a `--help` option to the `quick-lint-js` command-line utility which lists other supported options.

Detect `--help` in options.cpp, add a variable to the `option` struct in options.cpp, test the option parsing in test-option.cpp, and print the help message in main.cpp.

**Comment by jeduardofr** [comment]
dibs, i'm wclaytro by the way

**Comment by jeduardofr** [comment]
So, I added the option and I do the condition to check for it main.cpp. I was wondering about what format to use to print the message? Something man-like format?

**Comment by jeduardofr** [comment]
This should be close to avoid confusing people trying to contribute to the project.

**Comment by strager** [comment]
Commit 4455c73fdfd6b9b5e4160d73e7505101132619ba added the --help option.
