### ISSUE TITLE
Parse `with` statements

### ISSUE THREAD

**Issue by strager** [strager/quick-lint-js#13]
JavaScript has a rarely-used `with` statement. Make quick-lint-js parse such statements (instead of crashing) by augmenting parse.h.

I think `with` statements have a very similar syntax to `while` statements, so we might be able to copy-paste code to parse `with` statements.

Teaching the linter the semantics of `with` statements is out of scope for this task.

**Comment by CodeItQuick** [comment]
dibs!

**Comment by strager** [comment]
Landed in 02a6e22ae23ecb3ace075867457f0ba6397033d3.
