### ISSUE TITLE
Bug: quick-lint-test.exe fails to create temporary directory if hits QLJ64.tmp

### ISSUE THREAD

**Issue by LeeWannacott** [strager/quick-lint-js#18]
Related to Issue #12 

Running quick-lint-js-test.exe creates temp folders. 
If temp folder hits QLJ64.tmp and then quick quick-lint-test.exe is run it will complain: 'failed to create temporary directory'.

Note: You can access temp folder by using %temp%

Screenshot of bug:
![Screenshot (3)](https://user-images.githubusercontent.com/49783296/93044939-0a8b5c80-f6aa-11ea-9dc5-0d6ef12c3ac9.png)

**Comment by strager** [comment]
Thanks for reporting! Fixed in commit 58ed696e194dd883b7b1b6ab70151b6450e41e1f.
