### ISSUE TITLE
Support underscores in hex literals: 0x1234_5678

### ISSUE THREAD

**Issue by strager** [strager/quick-lint-js#31]
JavaScript supports underscores in number literals, including hex literals. quick-lint-js understands underscores in decimal literals (`123_456`), but doesn't understand underscores in hexadecimal literals (`0x1234_5678`).

Edit lex.cpp and test-lex.cpp to teach quick-lint-js to ignore underscores in hex literals.

**Comment by A-thanasios** [comment]
May I?

**Comment by arfire333** [comment]
See, it's not me.

**Comment by A-thanasios** [comment]
this is a public forum please refrain from deleting comments
