### ISSUE TITLE
Default loctation of qljs executable after building

### ISSUE THREAD

**Issue by vegerot** [strager/quick-lint-js#34]
When building qljs with `cmake --build .`, the executable is placed at `src/quick-lint-js`.

Not familiar other projects' patterns, but wondering if it is normal to place the compiled target in the `src` directory.

But, truth is, this whole issue was just an excuse to use GitHub CLI to create an issue.  And it was a resounding success

**Comment by strager** [comment]
> Not familiar other projects' patterns, but wondering if it is normal to place the compiled target in the `src` directory.

There's no standardization for developers.

End users run `make install` to put the executable in the correct place.

Do you want to put the executable somewhere else? I don't know what you're asking for in this GitHub issue.

**Comment by vegerot** [comment]
That is what I'm saying.  I know you'll eventually run `make install`.  But temporarily putting it in `src` is not what I've noticed in other projects.  I normally see it in another directory before you `make install` it.

Obviously not a big issue since this does not affect the eventual installation location.  But just something I wanted to point out, that at least confused me when I was first looking for the compiled product

**Comment by strager** [comment]
I moved the `quick-lint-js` executable out of the `src` directory. Does building Do The Right Thing now @vegerot ?
