### ISSUE TITLE
Parse 1_234_567 numbers

### ISSUE THREAD

**Issue by strager** [strager/quick-lint-js#4]
JavaScript number literals can contain underscores. quick-lint-js doesn't parse these as numbers, but it should.

Change lex.cpp and test-lex.cpp to teach quick-lint-js about number literals like 1_234_567.

**Comment by LeeWannacott** [comment]
I would like to attempt this issue.

**Comment by strager** [comment]
Fixed by @LeeWannacott in commit 9503baf002d654ccfaae54e70ce80c1a76f3aba4.
