### ISSUE TITLE
Report error for trailing underscores in number literals

### ISSUE THREAD

**Issue by strager** [strager/quick-lint-js#46]
If a number literal has trailing underscores (123_), the syntax is invalid. quick-lint-js should report an error for such constructs. Edit error.h, lex.cpp, and test-lex.cpp to make quick-lint-js help users find this bug.

**Comment by GauravPatil8778** [comment]
i want to work on this

**Comment by eiffel-fl** [comment]
Sorry @GauravPatil8778 I was not aware that we first have to say in the issue that we want to work on this...
Next time, I will first say that I want to work on it to avoid this problem...
