### ISSUE TITLE
Parse debugger statements

### ISSUE THREAD

**Issue by strager** [strager/quick-lint-js#6]
JavaScript has a `debugger` keyword which is used for ... debugging. quick-lint-js gets confused when it sees a `debugger` statement.

1. Tell quick-lint-js that `debugger` is a keyword, not a normal identifier. See lex.h, lex-keyword.gperf, and test-lex.cpp.
2. Teach quick-lint-js about `debugger` statements. See parse.h and test-parse.cpp. `debugger` statements should have no impact on the linter (I think).

**Comment by erlliam** [comment]
I will give this a try.

**Comment by strager** [comment]
@erlliam implemented `debugger` in #17.
