### ISSUE TITLE
Request: please rename `master` branch to something less colonial

### ISSUE THREAD

**Issue by vegerot** [strager/quick-lint-js#8]
Hello, Mr. Strager.  

I was looking for a fast way to lint our large javascript project when I came across this tool.  This looks great, unfortunately I have some pretty strong issues about the name of your default branch.

The `master` branch is a term from when slave-masters would force their slaves to write their tests and maintenance tickets, as well as updating their dependencies.

Since slavery has been abolished, I feel that it is best to remove this vestige of slavery by giving the main branch more inclusive name like main, prod, or release.

Thank you for taking the time to read this.  And if this racist code can be cleaned up a bit, I hope our team can start adopting quick-lint

**Comment by strager** [comment]
Maturity is a prerequisite for using quick-lint-js. I'll document that requirement later.

**Comment by vegerot** [comment]
Wow, you really thought a while about that response
